import { describe, expect, it } from 'vitest';

import { buildInitiativeVelocityCardArtifact } from '../src/scaffoldShareCard';
import { PROOF_SURFACE_QUIET_CTA } from '../src/widgetArtifactProof';

describe('scaffoldShareCard', () => {
  const artifact = buildInitiativeVelocityCardArtifact({
    hierarchy: {
      initiative: { title: 'Ship MCP App Store Listing' },
      workstreams: [
        {
          id: 'ws-1',
          domain: 'engineering',
          milestones: [{ id: 'ms-1', tasks: [{ id: 'task-1' }] }],
        },
      ],
    },
    initiativeId: 'init-12345678',
    liveUrl: 'https://useorgx.com/live/init-12345678',
  });

  it('closes the share card with the quiet CTA exactly once', () => {
    expect(PROOF_SURFACE_QUIET_CTA).toBe('Make your agent work resumable.');
    expect(
      artifact.preview_markdown.endsWith('Make your agent work resumable.')
    ).toBe(true);
    const occurrences =
      artifact.preview_markdown.split('Make your agent work resumable.')
        .length - 1;
    expect(occurrences).toBe(1);
  });

  it('exposes the quiet CTA to renderers as metadata', () => {
    expect(artifact.metadata.quiet_cta).toBe(
      'Make your agent work resumable.'
    );
  });

  it('keeps the existing share card copy intact', () => {
    expect(artifact.preview_markdown).toContain(
      '# Initiative Velocity Card: Ship MCP App Store Listing'
    );
    expect(artifact.preview_markdown).toContain(
      'Live view: https://useorgx.com/live/init-12345678'
    );
    expect(artifact.description).toBe(
      'Share-ready Initiative Velocity Card generated by scaffold_initiative and anchored to OrgX Live.'
    );
  });
});
