#!/usr/bin/env node
// Vendor the framework-free OrgX elements and tokens from @useorgx/orgx-ui-kit
// into public/widgets/shared/kit/. Widgets reference these paths and the MCP
// Apps resource builder inlines them (MCP_APPS_SHARED_COMPONENT_PATHS), so a
// widget never fetches the kit at runtime.
//
// The kit ships the elements whole (ox-elements.js) and split
// (ox-elements-core.js + ox-elements-{footer,glyph,avatar}.js add-ons that need
// core loaded first). Each widget loads only the bundles for the elements it
// uses; scripts/build-widgets.mjs checks the choice.
//
// Usage: ORGX_UI_KIT_DIR=../orgx-ui-kit node scripts/sync-ui-kit.mjs
// The kit must be built first (npm run build in the kit repo).
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const kitDir = resolve(root, process.env.ORGX_UI_KIT_DIR ?? '../orgx-ui-kit');
const outDir = resolve(root, 'public/widgets/shared/kit');
const pkg = JSON.parse(readFileSync(resolve(kitDir, 'package.json'), 'utf8'));
let commit = 'unknown';
try {
  commit = execFileSync('git', ['-C', kitDir, 'rev-parse', '--short=12', 'HEAD']).toString().trim();
} catch {}
const header = (comment) => comment(`@useorgx/orgx-ui-kit ${pkg.version} (${commit}). Generated by scripts/sync-ui-kit.mjs; do not edit.`);

mkdirSync(outDir, { recursive: true });
// dist file in the kit -> vendored file here.
const ELEMENT_BUNDLES = {
  'elements.iife.js': 'ox-elements.js',
  'elements-core.iife.js': 'ox-elements-core.js',
  'elements-footer.iife.js': 'ox-elements-footer.js',
  'elements-glyph.iife.js': 'ox-elements-glyph.js',
  'elements-avatar.iife.js': 'ox-elements-avatar.js',
};
for (const [from, to] of Object.entries(ELEMENT_BUNDLES)) {
  const body = readFileSync(resolve(kitDir, 'dist', from), 'utf8');
  writeFileSync(resolve(outDir, to), `${header((t) => `/* ${t} */`)}\n${body.trim()}\n`);
}
const tokens = readFileSync(resolve(kitDir, 'dist/tokens.css'), 'utf8');
writeFileSync(resolve(outDir, 'ox-tokens.css'), `${header((t) => `/* ${t} */`)}\n${tokens.trim()}\n`);
writeFileSync(resolve(outDir, 'VERSION.json'), `${JSON.stringify({ package: pkg.name, version: pkg.version, commit }, null, 2)}\n`);
console.log(`synced ${pkg.name}@${pkg.version} (${commit}) -> public/widgets/shared/kit`);
