/**
 * Matches OrgX app URLs against tests/fixtures/orgx-app-routes.json
 * (generated by scripts/generate-app-routes.mjs). Shared by the link-builder
 * route tests so server and widget links are held to the same app routes.
 */
import routesFixture from './orgx-app-routes.json';

export interface AppRoute {
  pattern: string;
  redirect: string | null;
  params: string[];
}

export interface AppRedirect {
  source: string;
  destination: string;
}

export const APP_ROUTES = routesFixture.routes as AppRoute[];
export const APP_REDIRECTS = routesFixture.redirects as AppRedirect[];

export interface AppRouteMatch {
  /** The page the path resolves to, or null when no page matches. */
  route: AppRoute | null;
  /** The next.config redirect the path hits before any page, if any. */
  configRedirect: AppRedirect | null;
  /** Query params on the URL that the matched page does not read. */
  unreadParams: string[];
}

function splitPath(pathname: string): string[] {
  return pathname.split('/').filter(Boolean).map((s) => decodeURIComponent(s));
}

/** Returns a specificity score (higher = more specific) or -1 when the pattern does not match. */
function matchSegments(pattern: string[], segments: string[]): number {
  let score = 0;
  for (let i = 0; i < pattern.length; i++) {
    const p = pattern[i];
    if (p.startsWith('[[...')) return i <= segments.length ? score : -1;
    if (p.startsWith('[...')) return segments.length > i ? score : -1;
    if (i >= segments.length) return -1;
    if (p.startsWith('[') || p.startsWith(':')) {
      score += 1;
    } else if (p === segments[i]) {
      score += 2;
    } else {
      return -1;
    }
  }
  return pattern.length === segments.length ? score : -1;
}

export function matchAppRoute(url: string): AppRouteMatch {
  const parsed = new URL(url, 'https://useorgx.com');
  const segments = splitPath(parsed.pathname);
  const queryKeys = [...new Set(parsed.searchParams.keys())];

  const configRedirect =
    APP_REDIRECTS.find((r) => matchSegments(splitPath(r.source), segments) >= 0) ?? null;

  let best: AppRoute | null = null;
  let bestScore = -1;
  for (const route of APP_ROUTES) {
    const score = matchSegments(splitPath(route.pattern), segments);
    if (score > bestScore) {
      best = route;
      bestScore = score;
    }
  }

  return {
    route: best,
    configRedirect,
    unreadParams: best ? queryKeys.filter((k) => !best!.params.includes(k)) : queryKeys,
  };
}

/** Describes why a URL does not land on a real page that reads its params, or null when it does. */
export function describeRouteProblem(url: string): string | null {
  const { route, configRedirect, unreadParams } = matchAppRoute(url);
  if (configRedirect) return `${url} hits next.config redirect ${configRedirect.source} -> ${configRedirect.destination}`;
  if (!route) return `${url} matches no page in the OrgX app`;
  if (route.redirect) return `${url} lands on ${route.pattern}, which redirects to ${route.redirect}`;
  if (unreadParams.length > 0) {
    return `${url} lands on ${route.pattern}, which does not read: ${unreadParams.join(', ')}`;
  }
  return null;
}
